name: april_json_translator
description: A tool that can translate json files from one language to another.
version: 0.0.2
homepage: 'https://github.com/AAAAAApril/JsonTranslator'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.2
  # https://pub.flutter-io.cn/packages/yaml
  yaml: ^3.1.1
  # https://pub.flutter-io.cn/packages/html
  html: ^0.15.1

dev_dependencies:
  # https://pub.flutter-io.cn/packages/build_runner
  build_runner: ^2.3.2

# 发布插件：命令行 执行命令
# flutter packages pub publish
# 或者
# flutter packages pub publish --server=https://pub.dartlang.org